#include "frontend/styles.h"
#include "raygui.h"
#include "globalVars/globalVars.h"

void setStyles()
{
    GuiSetStyle(DEFAULT, TEXT_SIZE, TEXT_FONT_SIZE);

    GuiSetStyle(TEXTBOX, TEXT_COLOR_NORMAL, 0x082100);
    GuiSetStyle(TEXTBOX, TEXT_COLOR_PRESSED, 0x082100);
    GuiSetStyle(TEXTBOX, BORDER_COLOR_NORMAL, ColorToInt(BLACK));
    GuiSetStyle(TEXTBOX, BORDER_COLOR_FOCUSED, ColorToInt(GRAY));
    GuiSetStyle(TEXTBOX, BORDER_COLOR_PRESSED, ColorToInt(GRAY));
    GuiSetStyle(TEXTBOX, BASE_COLOR_PRESSED, 0xF1C27B20);
    GuiSetStyle(TEXTBOX, BORDER_WIDTH, 2);

    GuiSetStyle(DROPDOWNBOX, BASE_COLOR_NORMAL, PRIMARY_COLOR_CONTAINER);
    GuiSetStyle(DROPDOWNBOX, BASE_COLOR_PRESSED, PRIMARY_COLOR_CONTAINER);
    GuiSetStyle(DROPDOWNBOX, BASE_COLOR_FOCUSED, PRIMARY_COLOR_CONTAINER_HOVER);
    GuiSetStyle(DROPDOWNBOX, BASE_COLOR_FOCUSED, PRIMARY_COLOR_CONTAINER_HOVER);

    GuiSetStyle(DROPDOWNBOX, TEXT_COLOR_NORMAL, TEXT_COLOR);
    GuiSetStyle(DROPDOWNBOX, TEXT_COLOR_FOCUSED, TEXT_COLOR);
    GuiSetStyle(DROPDOWNBOX, TEXT_COLOR_PRESSED, TEXT_COLOR);

    GuiSetStyle(DROPDOWNBOX, BORDER_COLOR_NORMAL, TEXT_COLOR);
    GuiSetStyle(DROPDOWNBOX, BORDER_COLOR_FOCUSED, TEXT_COLOR);
    GuiSetStyle(DROPDOWNBOX, BORDER_COLOR_PRESSED, TEXT_COLOR);

    GuiSetStyle(DROPDOWNBOX, TEXT_ALIGNMENT, TEXT_ALIGN_CENTER);
    GuiSetStyle(DROPDOWNBOX, DROPDOWN_ITEMS_SPACING, 0);

    GuiSetStyle(BUTTON, BASE_COLOR_NORMAL, PRIMARY_COLOR_CONTAINER);
    GuiSetStyle(BUTTON, BASE_COLOR_FOCUSED, PRIMARY_COLOR_CONTAINER_HOVER);
    GuiSetStyle(BUTTON, BASE_COLOR_PRESSED, OUTLINE_COLOR);

    GuiSetStyle(BUTTON, BORDER_COLOR_NORMAL, TEXT_COLOR);
    GuiSetStyle(BUTTON, BORDER_COLOR_FOCUSED, TEXT_COLOR);
    GuiSetStyle(BUTTON, BORDER_COLOR_PRESSED, TEXT_COLOR);

    GuiSetStyle(BUTTON, TEXT_COLOR_NORMAL, TEXT_COLOR);
    GuiSetStyle(BUTTON, TEXT_COLOR_FOCUSED, TEXT_COLOR);
    GuiSetStyle(BUTTON, TEXT_COLOR_PRESSED, TEXT_COLOR);

    GuiSetStyle(LISTVIEW, SCROLLBAR_WIDTH, 18);

    GuiSetFont(Resources::displayFontRegular);
}

